sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dOSnevIdpjHSWqx7d1x5VLNCSLd9XCKDyLgtC2H+38kGwt8AFWd/TWpe0oW8OCxB9YCFl/YyVBSxyq4ukFhxzkLWlQ7dG4VzXcssUDzdcojx+WM9CBNYvpHDkPsq17CIHZEZqQ1OuJJQBrZV/lWDVVQnHl11rHp0wtXZ+qXdRUf4dGs35OIT+LFBNoWpuraOvhGOKSgkSAiSwijlCPaJaTwfRxv35bNzeTEtMJHeIHO8U9Zu/gwwCYMnsjK8CfPbIKc0aeiiujGYn8MSICkO45rjBe4CG/FY41mZkP3rGZ7kR/kfldQL4R8rTxtGkbQ0I9GX++mI40vN8fqJ12FeRLuY9mQvBPW7I+DnASKAOMyxEf/iss4HWpWfuKnpRA1hfraH6J1V134n2JNw2foBz9gQ+EYB+hhwydBZyTy8YzUYTvxwd7dcVLPpkrx59Ud0TuL4QJBAlHcFG6TXXihuCVPb3UIL4aMdvX/P3NjJwXIdXJ3KD8jykdWIp1LYxldeuIsCen7aLKrlB4Y/EGI1uSj4R3EUIicqZol8coWQw1G4nPIPZCaFgnNj/Y388SuowXMutE6eU1tp7XMx2tm2Js0yWANHDzx0EZZ7gGYUmrnxTMSV/377sL7ZRN3Sf5KiLoRCAoQgn5JhEF386PVkspgXzR0vVE/wT+QsG8E7egg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Outlaw-of-Torn_369
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy